server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:model
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true

isa:
  model:
    url: http://localhost:8081/
    url.delete: /models/{id}
    url.put: /models/{id}
    url.post: /models